"""PreToolUse hook for Edit/Write/MultiEdit: refuse edits CLAUDE.md forbids.

- CHANGELOG.md is written by release-please only.
- A migration that is already on origin/main has been applied somewhere; write a new one.
- Real .env files hold secrets (.env.example is fine).

Exit code 2 blocks the tool call and shows stderr to Claude. Standard library only.
"""

import json
import os
import subprocess
import sys
from pathlib import Path, PurePosixPath
from typing import Any


def _repo_path(file_path: str, root: Path) -> PurePosixPath | None:
    try:
        return PurePosixPath(Path(file_path).resolve().relative_to(root.resolve()).as_posix())
    except ValueError:
        return None  # outside the repo: not ours to guard


def _on_main(path: PurePosixPath, root: Path) -> bool | None:
    """True or False when git can tell; None when it can't (no origin/main, no git).

    `git cat-file -e` exits 128 for both a missing path and a missing ref, so use
    `ls-tree`: exit 0 with empty output means the path is not on main.
    """
    try:
        result = subprocess.run(  # noqa: S603 - fixed argv, no shell
            ["git", "ls-tree", "--name-only", "origin/main", "--", str(path)],  # noqa: S607
            cwd=root,
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return None
    if result.returncode != 0:
        return None
    return bool(result.stdout.strip())


def reason_to_block(path: PurePosixPath, root: Path) -> str | None:
    if path.name == "CHANGELOG.md":
        return "CHANGELOG.md is generated by release-please from commit history. Do not edit it."
    if path.name == ".env" or (path.name.startswith(".env.") and path.name != ".env.example"):
        return "Real .env files hold secrets. Edit .env.example instead."
    if path.parent == PurePosixPath("backend/migrations/versions") and path.suffix == ".py":
        on_main = _on_main(path, root)
        if on_main is None:  # fail closed: an unknown migration may be an applied one
            return (
                f"Can't tell whether {path} is already on main (no origin/main ref). "
                "Run `git fetch origin main`, then retry."
            )
        if on_main:
            return (
                f"{path} is on main, so it has been applied. Never edit an applied migration: "
                'create a new one with `make migration m="..."`.'
            )
    return None


def main() -> int:
    try:
        return _check(json.load(sys.stdin))
    except Exception as exc:  # exit 1 would let the edit through, so fail closed
        sys.stderr.write(f"guard hook failed ({type(exc).__name__}: {exc}); edit blocked.\n")
        return 2


def _check(event: dict[str, Any]) -> int:
    file_path = event.get("tool_input", {}).get("file_path")
    if not file_path:
        return 0
    root = Path(os.environ.get("CLAUDE_PROJECT_DIR") or event.get("cwd") or ".")
    path = _repo_path(file_path, root)
    reason = path and reason_to_block(path, root)
    if reason:
        sys.stderr.write(reason + "\n")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
