"""PreToolUse hook for Edit/Write/MultiEdit: refuse edits CLAUDE.md forbids.

- CHANGELOG.md is written by release-please only.
- A migration that is already on origin/main has been applied somewhere; write a new one.
- Real .env files hold secrets (.env.example is fine).

Exit code 2 blocks the tool call and shows stderr to Claude. Standard library only.
"""

import json
import os
import subprocess
import sys
from pathlib import Path, PurePosixPath


def _repo_path(file_path: str, root: Path) -> PurePosixPath | None:
    try:
        return PurePosixPath(Path(file_path).resolve().relative_to(root.resolve()).as_posix())
    except ValueError:
        return None  # outside the repo: not ours to guard


def _on_main(path: PurePosixPath, root: Path) -> bool:
    result = subprocess.run(  # noqa: S603 - fixed argv, no shell
        ["git", "cat-file", "-e", f"origin/main:{path}"],  # noqa: S607
        cwd=root,
        capture_output=True,
        check=False,
    )
    return result.returncode == 0


def reason_to_block(path: PurePosixPath, root: Path) -> str | None:
    if path.name == "CHANGELOG.md":
        return "CHANGELOG.md is generated by release-please from commit history. Do not edit it."
    if path.name == ".env" or (path.name.startswith(".env.") and path.name != ".env.example"):
        return "Real .env files hold secrets. Edit .env.example instead."
    if (
        path.parent == PurePosixPath("backend/migrations/versions")
        and path.suffix == ".py"
        and _on_main(path, root)
    ):
        return (
            f"{path} is on main, so it has been applied. Never edit an applied migration: "
            'create a new one with `make migration m="..."`.'
        )
    return None


def main() -> int:
    event = json.load(sys.stdin)
    file_path = event.get("tool_input", {}).get("file_path")
    if not file_path:
        return 0
    root = Path(os.environ.get("CLAUDE_PROJECT_DIR") or event.get("cwd") or ".")
    path = _repo_path(file_path, root)
    reason = path and reason_to_block(path, root)
    if reason:
        sys.stderr.write(reason + "\n")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
