/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account/devices/{device_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign Out Device */
        delete: operations["sign_out_device_api_account_devices__device_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/passkeys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Passkey */
        delete: operations["remove_passkey_api_account_passkeys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/sign-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sign Ins */
        get: operations["sign_ins_api_account_sign_ins_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkeys/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_passkeys_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkeys/register/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registration Options
         * @description Options for adding a passkey to the signed-in person.
         */
        post: operations["registration_options_api_auth_passkeys_register_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkeys/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign In */
        post: operations["sign_in_api_auth_passkeys_sign_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/passkeys/sign-in/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign In Options
         * @description Options for signing in with a passkey; anyone may ask, only a registered key passes.
         */
        post: operations["sign_in_options_api_auth_passkeys_sign_in_options_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem
         * @description Exchange a one-time link from the bot for a session cookie.
         */
        post: operations["redeem_api_auth_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signout
         * @description End this browser's session. Harmless without one.
         */
        post: operations["signout_api_auth_signout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/pending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pending
         * @description Earlier days' guided sessions with sets but never saved, to offer saving them.
         */
        get: operations["pending_api_session_pending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Keep
         * @description Keep where the person is in today's session, so it resumes on any device. 409 when
         *     another device moved on since this browser's ``revision`` (reload and carry on).
         */
        put: operations["keep_api_session_progress_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save
         * @description Save the guided session as a workout: today's, or an earlier day's left unsaved.
         */
        post: operations["save_api_session_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/stretching/{workout_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stretching Routine
         * @description The stretches after a saved resistance workout, filling ``minutes`` (ADR-0032).
         */
        get: operations["stretching_routine_api_session_stretching__workout_id__get"];
        put?: never;
        /**
         * Stretching Done
         * @description Log the stretching minutes on the workout, once.
         */
        post: operations["stretching_done_api_session_stretching__workout_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today
         * @description Today's session in work order, with any pairs swapped as kept in the progress: a swap
         *     or un-swap is a PUT to /progress, so the server is the one place it lives.
         */
        get: operations["today_api_session_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Definitions
         * @description Every test, day 1 first.
         */
        get: operations["definitions_api_tests_get"];
        put?: never;
        /**
         * Save
         * @description Save a test day once (a repeated Save with the same token returns it).
         */
        post: operations["save_api_tests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tests/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Results
         * @description Every test day, newest first.
         */
        get: operations["results_api_tests_results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Answer
         * @description The browser's answer to a ceremony: WebAuthn JSON, checked by the library.
         */
        Answer: {
            /** Credential */
            credential: {
                [key: string]: unknown;
            };
        };
        /** BlockView */
        BlockView: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "strength" | "hypertrophy";
            /** Week */
            week: number;
        };
        /** DayView */
        DayView: {
            /** Day */
            day: number;
            /** Fed */
            fed: boolean;
            /** Id */
            id: number;
            /**
             * On
             * Format: date
             */
            on: string;
            /** Results */
            results: components["schemas"]["ResultView"][];
            /** Slept Well */
            slept_well: boolean;
            /**
             * Time Of Day
             * @enum {string}
             */
            time_of_day: "morning" | "midday" | "afternoon" | "evening";
        };
        /** DeviceView */
        DeviceView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current */
            current: boolean;
            /** Id */
            id: number;
            /** Label */
            label: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
        };
        /**
         * DoneView
         * @description A confirmed set; ``right`` only for one-sided exercises (empty: same as left).
         */
        DoneView: {
            /** Item */
            item: number;
            /** Left */
            left: number;
            /** Right */
            right?: number | null;
            /** Set No */
            set_no: number;
        };
        /** EarnedView */
        EarnedView: {
            /** Best Set */
            best_set: number | null;
            /** Exercise */
            exercise: string;
            /** Next Step */
            next_step: string | null;
            /** Total */
            total: number | null;
            /**
             * Unit
             * @enum {string}
             */
            unit: "reps" | "seconds" | "minutes";
        };
        /**
         * ExerciseKind
         * @description How an exercise is measured.
         * @enum {string}
         */
        ExerciseKind: "reps" | "seconds" | "duration_min";
        /** ExerciseView */
        ExerciseView: {
            kind: components["schemas"]["ExerciseKind"];
            /** Ladder */
            ladder: string[];
            /** Muscle Groups */
            muscle_groups: string[];
            /** Name */
            name: string;
            /** Per Side */
            per_side: boolean;
            /** Rep Max */
            rep_max: number;
            /** Rep Min */
            rep_min: number;
            /** Sets */
            sets: number;
            /** Slug */
            slug: string;
            /** Start Step */
            start_step: number;
        };
        /** GuidedView */
        GuidedView: {
            block: components["schemas"]["BlockView"] | null;
            /** Day */
            day: string;
            /** Focus */
            focus: string;
            /** Items */
            items: components["schemas"]["ItemView"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "strength" | "conditioning" | "recovery";
            /** Minutes */
            minutes: number;
            /** Name */
            name: string;
            /** Order */
            order: components["schemas"]["SetView"][];
            /** Rest Seconds */
            rest_seconds: number;
            /** Template Id */
            template_id: number;
            /** Warm Up */
            warm_up: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Bot Enabled */
            bot_enabled: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** ItemView */
        ItemView: {
            /** Baseline */
            baseline: boolean;
            /** Cue */
            cue: string | null;
            /** Name */
            name: string;
            /** Pair */
            pair: number | null;
            /** Per Side */
            per_side: boolean;
            /** Slug */
            slug: string;
            /** Step */
            step: string;
            /** Summary */
            summary: string | null;
            /** Targets */
            targets: number[];
            /**
             * Unit
             * @enum {string}
             */
            unit: "reps" | "seconds" | "minutes";
        };
        /** KeepBody */
        KeepBody: {
            /** First */
            first?: number[];
            /** Position */
            position: number;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /** Sets */
            sets?: components["schemas"]["DoneView"][];
            /** Template Id */
            template_id: number;
        };
        /** KeptView */
        KeptView: {
            /** Revision */
            revision: number;
        };
        /** Me */
        Me: {
            /** User Id */
            user_id: number;
        };
        /** PasskeyView */
        PasskeyView: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string;
        };
        /** PendingView */
        PendingView: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Session */
            session: string;
            /** Sets */
            sets: number;
        };
        /** PlanView */
        PlanView: {
            /** Sessions */
            sessions: components["schemas"]["SessionView"][];
            /** Volume */
            volume: components["schemas"]["VolumeView"][];
            /** Volume Target Max */
            volume_target_max: number;
            /** Volume Target Min */
            volume_target_min: number;
        };
        /** ProgressView */
        ProgressView: {
            /** First */
            first: number[];
            /** Position */
            position: number;
            /** Revision */
            revision: number;
            /** Saved */
            saved: boolean;
            /** Sets */
            sets: components["schemas"]["DoneView"][];
            /** Template Id */
            template_id: number;
        };
        /** Redeem */
        Redeem: {
            /** Token */
            token: string;
        };
        /** ResultView */
        ResultView: {
            /**
             * Side
             * @enum {string}
             */
            side: "both" | "left" | "right";
            /** Test */
            test: string;
            /** Value */
            value: number;
        };
        /** RoutineView */
        RoutineView: {
            /** Hold Seconds */
            hold_seconds: number;
            /** Minutes */
            minutes: number;
            /** Session */
            session: string;
            /** Steps */
            steps: components["schemas"]["StretchView"][];
        };
        /** SaveBody */
        SaveBody: {
            /** Day */
            day?: string | null;
        };
        /** SessionView */
        SessionView: {
            /** Exercises */
            exercises: components["schemas"]["ExerciseView"][];
            /** Focus */
            focus: string;
            /** Name */
            name: string;
            /** Optional */
            optional: boolean;
            /** Position */
            position: number;
            /** Slug */
            slug: string;
            /** Total Sets */
            total_sets: number;
            /**
             * Type
             * @enum {string}
             */
            type: "strength" | "conditioning" | "recovery";
        };
        /** SetView */
        SetView: {
            /** Item */
            item: number;
            /** Set No */
            set_no: number;
            /** Target */
            target: number;
        };
        /** SignIns */
        SignIns: {
            /** Devices */
            devices: components["schemas"]["DeviceView"][];
            /** Passkeys */
            passkeys: components["schemas"]["PasskeyView"][];
        };
        /** StretchBody */
        StretchBody: {
            /** Minutes */
            minutes: number;
        };
        /** StretchView */
        StretchView: {
            /** Cue */
            cue: string;
            /** Name */
            name: string;
            /** Per Side */
            per_side: boolean;
            /** Rounds */
            rounds: number;
        };
        /** StretchedView */
        StretchedView: {
            /** Logged */
            logged: boolean;
        };
        /** TestDayBody */
        TestDayBody: {
            /** Day */
            day: number;
            /** Fed */
            fed: boolean;
            /** On */
            on?: string | null;
            /** Results */
            results: components["schemas"]["ResultView"][];
            /** Slept Well */
            slept_well: boolean;
            /**
             * Time Of Day
             * @enum {string}
             */
            time_of_day: "morning" | "midday" | "afternoon" | "evening";
            /** Token */
            token: string;
        };
        /** TestView */
        TestView: {
            /** Cue */
            cue: string;
            /** Day */
            day: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Name */
            name: string;
            /** Per Side */
            per_side: boolean;
            /** Slug */
            slug: string;
            /**
             * Unit
             * @enum {string}
             */
            unit: "reps" | "seconds" | "metres" | "cm";
        };
        /**
         * TodayView
         * @description ``session`` is empty when nothing planned is left today (done or rested); ``progress``
         *     is where the person left off, to resume.
         */
        TodayView: {
            progress?: components["schemas"]["ProgressView"] | null;
            session: components["schemas"]["GuidedView"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VolumeView */
        VolumeView: {
            /** Group */
            group: string;
            /** Sets */
            sets: number;
        };
        /** SavedView */
        training_coach__api__fitness__SavedView: {
            /** Already Saved */
            already_saved: boolean;
            /** Id */
            id: number;
        };
        /** SavedView */
        training_coach__api__session__SavedView: {
            /** Already Saved */
            already_saved: boolean;
            /** Earned */
            earned: components["schemas"]["EarnedView"][];
            /** Next Session */
            next_session: string | null;
            /** Stretching */
            stretching: boolean;
            /** Workout Id */
            workout_id: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    sign_out_device_api_account_devices__device_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                device_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_passkey_api_account_passkeys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_ins_api_account_sign_ins_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignIns"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    register_api_auth_passkeys_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registration_options_api_auth_passkeys_register_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sign_in_api_auth_passkeys_sign_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Answer"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sign_in_options_api_auth_passkeys_sign_in_options_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    redeem_api_auth_redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Redeem"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signout_api_auth_signout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_plan_api_plan_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanView"];
                };
            };
        };
    };
    pending_api_session_pending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PendingView"][];
                };
            };
        };
    };
    keep_api_session_progress_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeepBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeptView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_api_session_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["training_coach__api__session__SavedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stretching_routine_api_session_stretching__workout_id__get: {
        parameters: {
            query: {
                minutes: number;
            };
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutineView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stretching_done_api_session_stretching__workout_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workout_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StretchBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StretchedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    today_api_session_today_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayView"];
                };
            };
        };
    };
    definitions_api_tests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestView"][];
                };
            };
        };
    };
    save_api_tests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestDayBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["training_coach__api__fitness__SavedView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    results_api_tests_results_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayView"][];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
