"""login link purpose

Revision ID: b82e2953d2b7
Revises: b082a8cf53e9
Create Date: 2026-10-10 05:58:19.776795

Sign-in links get a purpose (ADR-0040): start, refused once a passkey exists, or recover, which
signs out every other browser. Existing links are start links. Downgrade drops the column.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b82e2953d2b7"
down_revision: str | Sequence[str] | None = "b082a8cf53e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("login_links", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("purpose", sa.String(length=8), server_default="start", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("login_links", schema=None) as batch_op:
        batch_op.drop_column("purpose")

    # ### end Alembic commands ###
