"""session progress

Revision ID: fc2abe8399b4
Revises: 00649163c95b
Create Date: 2026-10-10 00:29:30.495367

Guided-session progress (D1, #117): one row per person per day with the position, swapped
pairs, confirmed sets and a revision (so a stale tab can't overwrite newer sets); a session
resumes on any device. New table only; downgrade drops it and any unsaved progress.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fc2abe8399b4"
down_revision: str | Sequence[str] | None = "00649163c95b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("first", sa.JSON(), nullable=False),
        sa.Column("sets", sa.JSON(), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("saved_workout_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["saved_workout_id"],
            ["workouts.id"],
            name=op.f("fk_session_progress_saved_workout_id_workouts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_templates.id"],
            name=op.f("fk_session_progress_template_id_session_templates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_session_progress_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_progress")),
        sa.UniqueConstraint(
            "user_id", "local_date", name=op.f("uq_session_progress_user_id_local_date")
        ),
    )
    with op.batch_alter_table("session_progress", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_progress_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_progress_user_id"))

    op.drop_table("session_progress")
    # ### end Alembic commands ###
