"""test days

Revision ID: ebd8768c0bec
Revises: bff147002c86
Create Date: 2026-10-10 01:56:38.082677

Test days (2-A, #94, ADR-0037): baseline tests and retests, with their conditions and
results. Downgrade drops the table and every result in it.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ebd8768c0bec"
down_revision: str | Sequence[str] | None = "bff147002c86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test_days",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("time_of_day", sa.String(length=16), nullable=False),
        sa.Column("fed", sa.Boolean(), nullable=False),
        sa.Column("slept_well", sa.Boolean(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("token", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "time_of_day IN ('morning', 'midday', 'afternoon', 'evening')",
            name=op.f("ck_test_days_time_of_day_valid"),
        ),
        sa.CheckConstraint("day IN (1, 2)", name=op.f("ck_test_days_day_valid")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_test_days_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test_days")),
        sa.UniqueConstraint("token", name=op.f("uq_test_days_token")),
    )
    with op.batch_alter_table("test_days", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_test_days_local_date"), ["local_date"], unique=False)
        batch_op.create_index(batch_op.f("ix_test_days_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("test_days", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_test_days_user_id"))
        batch_op.drop_index(batch_op.f("ix_test_days_local_date"))

    op.drop_table("test_days")
    # ### end Alembic commands ###
