"""weekly review time

Revision ID: 2f776c2d31ec
Revises: c8b760ed9e52
Create Date: 2026-10-07 16:55:37.055388

Sunday's weekly review time (#73), 19:00 for existing rows. Downgrade drops it: a time the
owner chose is lost, and the review goes back to 19:00 after a re-upgrade.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f776c2d31ec"
down_revision: str | Sequence[str] | None = "c8b760ed9e52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("review_time", sa.Time(), server_default="19:00:00.000000", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("review_time")

    # ### end Alembic commands ###
