"""retired exercises

Revision ID: 623c0007373b
Revises: af805783adbd
Create Date: 2026-10-09 13:40:15.827854

Retired exercises (#107, ADR-0034): out of the plan, kept with their history and still
loggable. per_side says how a retired exercise is logged, since no session item does. The seed
sets both from plan.toml on start. Downgrade drops them; retired exercises then look like any
exercise no session uses.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "623c0007373b"
down_revision: str | Sequence[str] | None = "af805783adbd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("retired", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )
        batch_op.add_column(
            sa.Column("per_side", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("exercises", schema=None) as batch_op:
        batch_op.drop_column("per_side")
        batch_op.drop_column("retired")

    # ### end Alembic commands ###
