"""workout log token

Revision ID: f58870988024
Revises: 8fa501cc9ce3
Create Date: 2026-10-06 23:07:10.578427

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f58870988024"
down_revision: str | Sequence[str] | None = "8fa501cc9ce3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("log_token", sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(batch_op.f("uq_workouts_log_token"), ["log_token"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_workouts_log_token"), type_="unique")
        batch_op.drop_column("log_token")

    # ### end Alembic commands ###
