"""plan_state queued sessions

Revision ID: 8fa501cc9ce3
Revises: 2e1d0e14ffb6
Create Date: 2026-10-06 20:59:38.603170

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fa501cc9ce3"
down_revision: str | Sequence[str] | None = "2e1d0e14ffb6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plan_state", schema=None) as batch_op:
        batch_op.add_column(sa.Column("queued", sa.JSON(), server_default="[]", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plan_state", schema=None) as batch_op:
        batch_op.drop_column("queued")

    # ### end Alembic commands ###
