"""progress photos

Revision ID: b082a8cf53e9
Revises: e12bc433f2ae
Create Date: 2026-10-10 04:20:05.756465

Progress photos (2-B, #143, ADR-0039): one JPEG per pose per day, metadata removed, kept in
the database so backups include it. Downgrade drops the table and every photo in it.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b082a8cf53e9"
down_revision: str | Sequence[str] | None = "e12bc433f2ae"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "progress_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("pose", sa.String(length=8), nullable=False),
        sa.Column("jpeg", sa.LargeBinary(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "pose IN ('front', 'side', 'back')", name=op.f("ck_progress_photos_pose_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_progress_photos_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_progress_photos")),
        sa.UniqueConstraint(
            "user_id", "local_date", "pose", name=op.f("uq_progress_photos_user_id_local_date_pose")
        ),
    )
    with op.batch_alter_table("progress_photos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_progress_photos_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("progress_photos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_progress_photos_user_id"))

    op.drop_table("progress_photos")
    # ### end Alembic commands ###
