"""measurements

Revision ID: e12bc433f2ae
Revises: ebd8768c0bec
Create Date: 2026-10-10 02:50:53.447865

Body measurements (2-B, #142): one value per kind per day, in tenths. Personal data:
never logged or shared. Downgrade drops the table and every measurement in it.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e12bc433f2ae"
down_revision: str | Sequence[str] | None = "ebd8768c0bec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "measurements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("tenths", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('bodyweight', 'waist', 'chest', 'upper_arm', 'thigh', 'resting_hr')",
            name=op.f("ck_measurements_kind_valid"),
        ),
        sa.CheckConstraint("tenths > 0", name=op.f("ck_measurements_tenths_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_measurements_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_measurements")),
        sa.UniqueConstraint(
            "user_id", "local_date", "kind", name=op.f("uq_measurements_user_id_local_date_kind")
        ),
    )
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_measurements_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("measurements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_measurements_user_id"))

    op.drop_table("measurements")
    # ### end Alembic commands ###
