"""session passkey

Revision ID: 67b704aac1e8
Revises: b82e2953d2b7
Create Date: 2026-10-10 08:16:24.014032

A signed-in browser records the passkey that started it, so removing the key ends its
sessions (security review). Existing sessions have none. Downgrade drops the column.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67b704aac1e8"
down_revision: str | Sequence[str] | None = "b82e2953d2b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("passkey_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_web_sessions_passkey_id"), ["passkey_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_web_sessions_passkey_id_passkeys"),
            "passkeys",
            ["passkey_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_web_sessions_passkey_id_passkeys"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_web_sessions_passkey_id"))
        batch_op.drop_column("passkey_id")

    # ### end Alembic commands ###
