"""passkeys

Revision ID: ce6cab8be348
Revises: 391597c72151
Create Date: 2026-10-09 22:15:21.823000

Passkeys (ADR-0036, #115): each person's registered fingerprint/face keys (public halves
only), and one-time WebAuthn challenges. New tables only; downgrade drops them, and passkeys
must then be registered again.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce6cab8be348"
down_revision: str | Sequence[str] | None = "391597c72151"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passkey_challenges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("handle_hash", sa.String(length=64), nullable=False),
        sa.Column("challenge", sa.LargeBinary(), nullable=False),
        sa.Column("purpose", sa.String(length=16), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "purpose IN ('register', 'sign_in')", name=op.f("ck_passkey_challenges_purpose_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_passkey_challenges_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passkey_challenges")),
        sa.UniqueConstraint("handle_hash", name=op.f("uq_passkey_challenges_handle_hash")),
    )
    op.create_table(
        "passkeys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.String(length=1400), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_passkeys_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_passkeys")),
        sa.UniqueConstraint("credential_id", name=op.f("uq_passkeys_credential_id")),
    )
    with op.batch_alter_table("passkeys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_passkeys_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("passkeys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_passkeys_user_id"))

    op.drop_table("passkeys")
    op.drop_table("passkey_challenges")
    # ### end Alembic commands ###
