"""habit checks

Revision ID: 2fb51b85915d
Revises: ce8ddc5b9be1
Create Date: 2026-10-07 22:56:18.029475

Habit check-offs (D5, #90): one row per habit ticked per day, per person (ADR-0029). A new
table only; downgrade drops it and every check-off with it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fb51b85915d"
down_revision: str | Sequence[str] | None = "ce8ddc5b9be1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "habit_checks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("habit", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "habit IN ('morning_light', 'protein', 'wind_down')",
            name=op.f("ck_habit_checks_habit_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_habit_checks_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_habit_checks")),
        sa.UniqueConstraint(
            "user_id", "local_date", "habit", name=op.f("uq_habit_checks_user_id_local_date_habit")
        ),
    )
    with op.batch_alter_table("habit_checks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_habit_checks_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("habit_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_habit_checks_user_id"))

    op.drop_table("habit_checks")
    # ### end Alembic commands ###
