"""protein target

Revision ID: 63727d425df4
Revises: 623c0007373b
Create Date: 2026-10-09 20:37:37.162909

The daily protein target for the protein habit, in grams; empty until set in /settings.
Downgrade drops it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63727d425df4"
down_revision: str | Sequence[str] | None = "623c0007373b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("protein_g", sa.Integer(), nullable=True))
        batch_op.create_check_constraint(
            "protein_g_range", "protein_g IS NULL OR protein_g BETWEEN 40 AND 400"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_constraint("protein_g_range", type_="check")
        batch_op.drop_column("protein_g")

    # ### end Alembic commands ###
