"""plan versions

Revision ID: bff147002c86
Revises: fc2abe8399b4
Create Date: 2026-10-10 01:33:03.861911

Plan versions (#107, ADR-0034): each in force from its date until the next. Every workout
records the version in force on its date; the seed adds the versions from plan.toml and fills
in workouts saved before them. Downgrade drops both; workouts then carry no version.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bff147002c86"
down_revision: str | Sequence[str] | None = "fc2abe8399b4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("since", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_versions")),
        sa.UniqueConstraint("since", name=op.f("uq_plan_versions_since")),
    )
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("plan_version_id", sa.Integer(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_workouts_plan_version_id"), ["plan_version_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_workouts_plan_version_id_plan_versions"),
            "plan_versions",
            ["plan_version_id"],
            ["id"],
            ondelete="RESTRICT",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_workouts_plan_version_id_plan_versions"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_workouts_plan_version_id"))
        batch_op.drop_column("plan_version_id")

    op.drop_table("plan_versions")
    # ### end Alembic commands ###
