"""exercise pairs

Revision ID: af805783adbd
Revises: 2ab9760ba479
Create Date: 2026-10-08 05:40:32.458204

Exercise pairs (#97, ADR-0031): items sharing a number are done alternately. The seed fills
them in from plan.toml on start; until it does (or if it fails, ADR-0015) every item is done
alone, as before. Downgrade drops the column.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af805783adbd"
down_revision: str | Sequence[str] | None = "2ab9760ba479"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template_items", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pair", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("template_items", schema=None) as batch_op:
        batch_op.drop_column("pair")

    # ### end Alembic commands ###
