"""web sign-in

Revision ID: 391597c72151
Revises: 63727d425df4
Create Date: 2026-10-09 21:46:11.591504

Web sign-in (ADR-0036, #115): one-time links from the bot and signed-in browser sessions,
per person (ADR-0029), both storing only SHA-256 hashes of their tokens. New tables only;
downgrade drops them and signs everyone out.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "391597c72151"
down_revision: str | Sequence[str] | None = "63727d425df4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_links",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_login_links_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_links")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_login_links_token_hash")),
    )
    with op.batch_alter_table("login_links", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_login_links_user_id"), ["user_id"], unique=False)

    op.create_table(
        "web_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_web_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_web_sessions_token_hash")),
    )
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_web_sessions_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("web_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_web_sessions_user_id"))

    op.drop_table("web_sessions")
    with op.batch_alter_table("login_links", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_links_user_id"))

    op.drop_table("login_links")
    # ### end Alembic commands ###
