"""training blocks

Revision ID: ce8ddc5b9be1
Revises: 2f776c2d31ec
Create Date: 2026-10-07 18:40:12.604313

Training blocks (ADR-0028, #26): each session's kind from plan.toml, the day blocks started, and
the block each workout was logged in. The bundled plan's non-strength sessions get their kind
here, so a failed seed (ADR-0015) can't leave cardio marked as strength; the seed keeps kinds in
step with plan.toml after that. Downgrade drops them: the block each workout was logged in and
whether blocks are on are lost.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce8ddc5b9be1"
down_revision: str | Sequence[str] | None = "2f776c2d31ec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

KINDS = {
    "recovery": "recovery",
    "moderate-cardio": "conditioning",
    "hiit": "conditioning",
    "zone2": "conditioning",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session_templates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("kind", sa.String(length=16), server_default="strength", nullable=False)
        )
        batch_op.create_check_constraint(
            "kind_valid", "kind IN ('strength', 'conditioning', 'recovery')"
        )
    # The bundled plan's sessions as of this migration (migrations never import app code).
    for slug, kind in KINDS.items():
        op.execute(
            sa.text("UPDATE session_templates SET kind = :kind WHERE slug = :slug").bindparams(
                kind=kind, slug=slug
            )
        )

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("blocks_started_on", sa.Date(), nullable=True))

    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("block", sa.String(length=16), nullable=True))
        batch_op.create_check_constraint("block_valid", "block IN ('strength', 'hypertrophy')")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_constraint("block_valid", type_="check")
        batch_op.drop_column("block")

    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("blocks_started_on")

    with op.batch_alter_table("session_templates", schema=None) as batch_op:
        batch_op.drop_constraint("kind_valid", type_="check")
        batch_op.drop_column("kind")

    # ### end Alembic commands ###
