"""phase 1 data model

Revision ID: 2e1d0e14ffb6
Revises:
Create Date: 2026-09-29 18:51:57.420956

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e1d0e14ffb6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("at", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_at"), ["at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_kind"), ["kind"], unique=False)

    op.create_table(
        "exercises",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("muscle_groups", sa.JSON(), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('reps', 'seconds', 'duration_min')", name=op.f("ck_exercises_kind_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercises")),
        sa.UniqueConstraint("slug", name=op.f("uq_exercises_slug")),
    )
    op.create_table(
        "session_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("focus", sa.String(length=120), nullable=False),
        sa.Column("is_rest_optional", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_session_templates_position_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session_templates")),
        sa.UniqueConstraint("position", name=op.f("uq_session_templates_position")),
        sa.UniqueConstraint("slug", name=op.f("uq_session_templates_slug")),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("morning_time", sa.Time(), nullable=False),
        sa.Column("nudge_time", sa.Time(), nullable=False),
        sa.Column("nudges_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False),
        sa.Column("paused", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_table(
        "ladder_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("cue", sa.Text(), nullable=True),
        sa.CheckConstraint("position >= 0", name=op.f("ck_ladder_steps_position_non_negative")),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_ladder_steps_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ladder_steps")),
        sa.UniqueConstraint("exercise_id", "id", name=op.f("uq_ladder_steps_exercise_id_id")),
        sa.UniqueConstraint(
            "exercise_id", "position", name=op.f("uq_ladder_steps_exercise_id_position")
        ),
    )
    op.create_table(
        "plan_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("next_template_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_plan_state_single_row")),
        sa.ForeignKeyConstraint(
            ["next_template_id"],
            ["session_templates.id"],
            name=op.f("fk_plan_state_next_template_id_session_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_state")),
    )
    op.create_table(
        "template_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("sets", sa.Integer(), nullable=False),
        sa.Column("rep_min", sa.Integer(), nullable=False),
        sa.Column("rep_max", sa.Integer(), nullable=False),
        sa.Column("per_side", sa.Boolean(), server_default=sa.text("0"), nullable=False),
        sa.CheckConstraint("position >= 0", name=op.f("ck_template_items_position_non_negative")),
        sa.CheckConstraint("rep_max >= rep_min", name=op.f("ck_template_items_rep_range_valid")),
        sa.CheckConstraint("rep_min >= 1", name=op.f("ck_template_items_rep_min_positive")),
        sa.CheckConstraint("sets >= 1", name=op.f("ck_template_items_sets_positive")),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_template_items_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_templates.id"],
            name=op.f("fk_template_items_template_id_session_templates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_template_items")),
        sa.UniqueConstraint(
            "template_id", "position", name=op.f("uq_template_items_template_id_position")
        ),
    )
    op.create_table(
        "workouts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("local_date", sa.Date(), nullable=False),
        sa.Column("template_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('done', 'rest', 'skipped')", name=op.f("ck_workouts_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["session_templates.id"],
            name=op.f("fk_workouts_template_id_session_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workouts")),
    )
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_workouts_local_date"), ["local_date"], unique=False)

    op.create_table(
        "exercise_state",
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("ladder_step_id", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_id", "ladder_step_id"],
            ["ladder_steps.exercise_id", "ladder_steps.id"],
            name=op.f("fk_exercise_state_exercise_id_ladder_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_exercise_state_exercise_id_exercises"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("exercise_id", name=op.f("pk_exercise_state")),
    )
    op.create_table(
        "set_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workout_id", sa.Integer(), nullable=False),
        sa.Column("exercise_id", sa.Integer(), nullable=False),
        sa.Column("ladder_step_id", sa.Integer(), nullable=False),
        sa.Column("set_no", sa.Integer(), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("side", sa.String(length=8), server_default="both", nullable=False),
        sa.CheckConstraint(
            "side IN ('both', 'left', 'right')", name=op.f("ck_set_logs_side_valid")
        ),
        sa.CheckConstraint("set_no >= 1", name=op.f("ck_set_logs_set_no_positive")),
        sa.CheckConstraint("value >= 0 AND value <= 3600", name=op.f("ck_set_logs_value_in_range")),
        sa.ForeignKeyConstraint(
            ["exercise_id", "ladder_step_id"],
            ["ladder_steps.exercise_id", "ladder_steps.id"],
            name=op.f("fk_set_logs_exercise_id_ladder_steps"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["exercise_id"],
            ["exercises.id"],
            name=op.f("fk_set_logs_exercise_id_exercises"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workout_id"],
            ["workouts.id"],
            name=op.f("fk_set_logs_workout_id_workouts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_set_logs")),
        sa.UniqueConstraint(
            "workout_id",
            "exercise_id",
            "set_no",
            "side",
            name=op.f("uq_set_logs_workout_id_exercise_id_set_no_side"),
        ),
    )
    with op.batch_alter_table("set_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_set_logs_exercise_id"), ["exercise_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_set_logs_workout_id"), ["workout_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("set_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_set_logs_workout_id"))
        batch_op.drop_index(batch_op.f("ix_set_logs_exercise_id"))

    op.drop_table("set_logs")
    op.drop_table("exercise_state")
    with op.batch_alter_table("workouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_workouts_local_date"))

    op.drop_table("workouts")
    op.drop_table("template_items")
    op.drop_table("plan_state")
    op.drop_table("ladder_steps")
    op.drop_table("settings")
    op.drop_table("session_templates")
    op.drop_table("exercises")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_kind"))
        batch_op.drop_index(batch_op.f("ix_events_at"))

    op.drop_table("events")
    # ### end Alembic commands ###
