"""habits setting

Revision ID: 2ab9760ba479
Revises: 2fb51b85915d
Create Date: 2026-10-07 23:04:27.925538

Habit buttons on or off (D5, #91); on for everyone, as the habits were chosen together.
Downgrade drops the column, and the choice with it.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ab9760ba479"
down_revision: str | Sequence[str] | None = "2fb51b85915d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("habits_enabled", sa.Boolean(), server_default=sa.text("1"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("settings", schema=None) as batch_op:
        batch_op.drop_column("habits_enabled")

    # ### end Alembic commands ###
